<?php include __DIR__ . '/../components/header.phtml'; ?>
<main class="container">
  <section class="row">
    <aside class="col-12 col-md-3 p-2">
      <div class="row m-0 mb-4">
        <p class="fw-bold fs-4 m-0">PROFILE</p>
        <small class="text-secondary m-0">Manage your account</small>
      </div>
      <nav>
        <ul class="nav nav-pills flex-column">
          <li class="nav-items">
            <a class="nav-link" href="/dashboard">
              <i class="bi bi-collection-fill me-2"></i>
              Dashboard
            </a>
          </li>
          <li class="nav-items">
            <a class="nav-link" href="/loans">
              <i class="bi bi-postcard-fill me-2"></i>
              Loans
            </a>
          </li>
          <li class="nav-items">
            <a class="nav-link" href="/books">
              <i class="bi bi-book-fill me-2"></i>
              Books
            </a>
          </li>
          <li class="nav-items">
            <a class="nav-link " href="/members">
              <i class="bi bi-people-fill me-2"></i>
              Members
            </a>
          </li>
          <li class="nav-items">
            <a class="nav-link disabled text-secondary" disabled>
              <i class="bi bi-caret-right-square-fill me-2"></i>
              Reservation (soon)
            </a>
          </li>
          <li class="nav-items">
            <a class="nav-link active" href="/profile">
              <i class="bi bi-person-fill me-2"></i>
              Profile
            </a>
          </li>
        </ul>
      </nav>
    </aside>

    <div
      class="d-none d-md-flex col-1 p-0 mx-1 bg-secondary"
      style="width: 1px"
    ></div>

    <div class="col p-2">
      <?php include __DIR__ . '/main-profile.phtml'; ?>
    </div>

  </section>
</main>
<?php include __DIR__ . '/../components/footer.phtml'; ?>
