<div class="container-fluid mb-3">
  <div class="row mb-4">
    <div class="col">
      <p class="fw-bold fs-4 m-0">OVERVIEW</p>
      <small class="text-secondary m-0">Stats from this week</small>
    </div>
  </div>
  <div class="row g-4">
    <div class="col-12 col-md-6">
      <div class="card h-100 shadow-sm">
        <div class="card-body">
          <div class="d-flex justify-content-between align-items-start">
            <div>
              <h6 class="text-body-secondary mb-2">Books</h6>
              <h2 class="mb-1">00</h2>
              <small class="text-body-secondary"> Registered Books </small>
            </div>
            <div class="fs-2">
              <i class="bi bi-collection-fill"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-6">
      <div class="card h-100 shadow-sm">
        <div class="card-body">
          <div class="d-flex justify-content-between align-items-start">
            <div>
              <h6 class="text-body-secondary mb-2">Clients</h6>
              <h2 class="mb-1">00</h2>
              <small class="text-body-secondary"> Registered Clients </small>
            </div>

            <div class="fs-2">
              <i class="bi bi-people-fill"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-6">
      <div class="card h-100 shadow-sm">
        <div class="card-body">
          <div class="d-flex justify-content-between align-items-start">
            <div>
              <h6 class="text-body-secondary mb-2">Active Loans</h6>
              <h2 class="mb-1">00</h2>
              <small class="text-success"> 00 within the deadline </small>
            </div>
            <div class="fs-2">
              <i class="bi bi-book-fill"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-6">
      <div class="card h-100 shadow-sm">
        <div class="card-body">
          <div class="d-flex justify-content-between align-items-start">
            <div>
              <h6 class="text-body-secondary mb-2">Delay</h6>
              <h2 class="mb-1">00</h2>
              <small class="text-danger"> Warning </small>
            </div>
            <div class="fs-2">
              <i class="bi bi-exclamation-triangle-fill"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-12">
      <div class="card shadow-sm">
        <div
          class="card-header bg-body d-flex justify-content-between align-items-center"
        >
          <div>
            <h5 class="mb-0">Recents Loans</h5>
            <small class="text-body-secondary"> Last moviments </small>
          </div>

          <a href="/loans" class="btn btn-sm btn-outline-primary"> See more </a>
        </div>

        <div class="table-responsive">
          <table class="table table-hover align-middle mb-0">
            <thead>
              <tr>
                <th>Client</th>
                <th>Book</th>
                <th>Loan</th>
                <th>Return</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>NAME PERSON</td>
                <td>BOOK TITLE</td>
                <td>LOAN DATE</td>
                <td>RETURN DATE</td>
                <td>
                  <span class="badge text-bg-success"> active </span>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
