<footer class="border-top border-secondary mb-3">
  <div class="container">
    <div
      class="d-flex flex-column flex-md-row justify-content-between gap-4 py-4"
    >
      <div class="d-flex flex-column">
        <h2 class="fw-bold fs-5 mb-1">
          <i class="bi bi-book-half"></i>
          Library System
        </h2>
        <p class="text-secondary fs-6 mb-0">v1.2.0 (Demo)</p>
        <p class="text-secondary small mt-2 mb-0">
          Demo version — May contain errors or incomplete features.
        </p>
      </div>
      <div>
        <h6 class="fw-bold mb-3">Social</h6>
        <div class="d-flex gap-2">
          <a
            class="btn btn-outline-primary"
            href="https://github.com/lapollivinicius/library-system/"
            aria-label="GitHub"
            target="_blank"
          >
            <i class="bi bi-github"></i>
            Github
          </a>
          <a
            class="btn btn-outline-primary"
            href="https://linkedin.com/in/lapollivinicius"
            aria-label="LinkedIn"
            target="_blank"
          >
            <i class="bi bi-linkedin"></i>
            Linkedin
          </a>
        </div>
      </div>
    </div>

    <div class="border-top border-secondary py-3">
      <div
        class="d-flex flex-column flex-md-row justify-content-between align-items-center gap-2"
      >
        <p class="text-secondary small mb-0">
          © 2026 Library System. All rights reserved • MIT LICENSE.
        </p>
        <p class="text-secondary small mb-0">
          Built by <?php include __DIR__ .
          '/../../public/components/cadeirada.phtml'; ?>
          <a
            class="link-danger fw-bold link-underline-opacity-0"
            href="https://cadeiradaestudio.com/en"
            target="_blank"
            >estúdio cadeiradas</a
          >
        </p>
      </div>
    </div>
  </div>
</footer>
