<header class="border-bottom border-secondary">
  <div class="container">
    <div class="d-flex justify-content-between align-items-center py-3">
      <a
        href="/dashboard"
        class="text-decoration-none text-body d-flex align-items-center gap-2">
        <i class="bi bi-book-half text-primary fs-4"></i>
        <div class="d-flex flex-column">
          <span class="fw-bold"> Library System </span>
          <small class="text-secondary text-capitalize">
            <?= $_SESSION['library_name'] ?>
          </small>
        </div>
      </a>
      <div class="d-flex align-items-center gap-2">
        <a href="/profile" class="btn btn-outline-primary" title="Profile">
          <i class="bi bi-person-fill"></i>
          <span class="d-none d-lg-inline ms-1"> <?php echo ucfirst($_SESSION['name']) ?? 'Profile' ?> • Admin </span>
        </a>
        <form action="/auth/logout" method="POST">
          <input
            type="hidden"
            name="csrf_token"
            value="<?php echo $this->view->csrf_token; ?>" />
          <button type="submit" class="btn btn-outline-danger" title="Logout">
            <i class="bi bi-box-arrow-right"></i>
            <span class="d-none d-lg-inline ms-1"> Logout </span>
          </button>
        </form>
        <button type="button" class="theme-toggle btn btn-outline-secondary">
          <i class="bi bi-moon"></i>
        </button>
      </div>
    </div>
  </div>
  <script src="/js/sign.js"></script>
</header>
