services:
  php:
    build:
      context: .
      dockerfile: dockerfile
    container_name: php
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - php_app

  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306" # remove in production
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - php_app

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - php_app

networks:
  php_app:
    driver: bridge