services:
  php:
    image: php:8.3-apache
    container_name: php
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - php_app

  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"  # ports expose database - remove in production
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - php_app

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - php_app

networks:
  php_app:
    driver: bridge