<?php include __DIR__ . '/components/header.phtml'; ?>
<main class="py-5">
  <section class="session min-vh-75 d-flex align-items-center py-5">
    <div class="container">
      <div class="wrapper">
        <div class="row justify-content-center text-center">
          <div class="col-12 col-md-8 col-lg-6">
            <div class="mb-2">
              <i class="bi bi-box-arrow-in-right text-primary display-1"></i>
              <h1 class="display-3 fw-bold text-primary mb-0">Did you forget?</h1>
              <h2 class="fw-bold mt-3">It happens. We'll bounce back.</h2>
            </div>
            <div class="mt-4">
              <form action="/auth/recovery" method="POST" class="d-flex flex-column align-items-center">
                <input
                  type="hidden"
                  name="csrf_token"
                  value="<?php echo $this->view->csrf_token; ?>"
                />
                <div class="mb-3">
                  <input type="email" name="email" id="email" class="form-control" placeholder="Please, inform your e-mail" required>
                  <div id="passwordHelpBlock" class="form-text">
                    we'll send you an e-mail, verify to reset your password
                  </div>
                </div>
                <div>
                  <button type="submit" class="btn btn-primary me-2">
                    <i class="bi bi-send"></i>
                    send e-mail
                  </button>
                  <a href="/" class="btn btn-primary">
                    <i class="bi bi-house me-2"></i>
                    Back to home
                  </a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>
<?php include __DIR__ . '/components/footer.phtml'; ?>