<h1>REGISTER</h1>
<form class="form" action="/auth/register" method="POST">
    <input class="input-control" type="text" name="name" placeholder="name">
    <input class="input-control" type="text" name="username" placeholder="username">
    <input class="input-control" type="password" name="password" placeholder="password">
    <input class="input-control" type="email" name="email" placeholder="email">
    <input class="input-control" type="text" name="phone" placeholder="phone">
    <button class="btn btn-dark" type="submit">LOGIN</button>
</form>

<!-- :name, :username, :password, :email, :phone, :documen -->