<!DOCTYPE html>
<html lang="en" data-bs-theme="light">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="Library System" />
    <meta
      name="description"
      content="Manage your library, track loans, and monitor book reservations with ease."
    />
    <!-- META OG
    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="Library System" />
    <meta
      property="og:title"
      content="Library System | A library mananger"
    />
    <meta
      property="og:description"
      content="Manage your library, track loans, and monitor book reservations with ease."
    />
    <meta property="og:url" content="https://librarysystem.live" />
    <meta property="og:image" content="https://librarysystem.live/og.png" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta
      name="twitter:title"
      content="Library System | A library mananger"
    />
    <meta
      name="twitter:description"
      content="Manage your library, track loans, and monitor book reservations with ease."
    />
    <meta name="twitter:image" content="https://librarysystem.live/og.png" />
    -->
    <title>
      Library System<?php echo (' | ' . ucfirst($this->view->title)) ?? '' ?>
    </title>
    <link rel="stylesheet" href="/css/style.css" />
    <link rel="shortcut icon" href="/assets/favicon.ico" type="image/x-icon" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://code.jquery.com/jquery-4.0.0.min.js"
      integrity="sha256-OaVG6prZf4v69dPg6PhVattBXkcOWQB62pdZ3ORyrao="
      crossorigin="anonymous"
    ></script>
    <script src="/js/script.js"></script>
    <script>
      const theme = localStorage.getItem("theme");
      if (theme) {
        document.documentElement.setAttribute("data-bs-theme", theme);
      }
    </script>
  </head>

  <body>
    <?php include __DIR__ . '/modals/modal-confirm.phtml'; ?> <?=
    $this->content(); ?> <?php include __DIR__ .
    '/public/components/cookie.phtml'; ?>
  </body>
</html>
